# Generated by Django 5.1.4 on 2024-12-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='choice_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
